### PR TITLE
Android 6 & 7 Support

### PR DESCRIPTION
**Pull request by YT-Advanced**

### CODE REVIEW

**Comment by g10drasingh** [comment]
Since, there is no way to report issues on this. I am reporting here
The latest release uses PowerTube as download manager, however when clicking on download button it shows error. Below is the output of error
**Display error**
We're sorry...

What happened?

Unknown error

x86: Fields [format id, id, title, url] are

required for type with serial name

'ussr.razar.youtube_dl.json.kotlinx.Server JSONSingleSmall", but they were missing

**PowerTube Error log**

AMELI-> Log stated at 1684673948942

1684673948984: AMELI---> URL AMELI---> https://youtu.be/uDFIVtMAIZK

1684673948984:

1684673948984: AMELI---> Video id

1684673948984: AMELI---> UDFIVtMAIZK

1684673950001: AMELI---> Load URL

1684673950001: AMELI---> https://www.youtube.com

/watch?v=uDFIVtMAIZk&has_verified=1&bpctr=9999999999 1684673950624: AMELI---> StreamData decode


1684673950633: AMELI---> JSON Parsed

1684673950634: AMELI---> Dechiper Load problem

1684673953136: AMELI-> Exception: enc

1684673953136: AMELI---> java.lang.Exception: Could not

parse deobfuscate function 1684673953136:

AMELI>Sorting

AMELI---> URL https://youtu.be/uDFIVtMAIZK

AMELI--> Detected extractor None AMELI---> URL https://youtu.be/uDFIVtMAIZK

AMELI---> Detected extractor YouTube

Also, there is no option to change the default download manager. Can you provide the option to change download manager in future releases?

**Comment by datlmhg** [comment]
it's been many days but no new update

**Comment by NoName-exe** [comment]
Honestly,those who want Android 7 support can fork this repo and build it. It's pretty easy anyways.

**Comment by NoName-exe** [comment]
> Since, there is no way to report issues on this. I am reporting here
> The latest release uses PowerTube as download manager, however when clicking on download button it shows error. Below is the output of error
> **Display error**
> We're sorry...
> 
> What happened?
> 
> Unknown error
> 
> x86: Fields [format id, id, title, url] are
> 
> required for type with serial name
> 
> 'ussr.razar.youtube_dl.json.kotlinx.Server JSONSingleSmall", but they were missing
> 
> **PowerTube Error log**
> 
> AMELI-> Log stated at 1684673948942
> 
> 1684673948984: AMELI---> URL AMELI---> https://youtu.be/uDFIVtMAIZK
> 
> 1684673948984:
> 
> 1684673948984: AMELI---> Video id
> 
> 1684673948984: AMELI---> UDFIVtMAIZK
> 
> 1684673950001: AMELI---> Load URL
> 
> 1684673950001: AMELI---> https://www.youtube.com
> 
> /watch?v=uDFIVtMAIZk&has_verified=1&bpctr=9999999999 1684673950624: AMELI---> StreamData decode
> 
> 
> 1684673950633: AMELI---> JSON Parsed
> 
> 1684673950634: AMELI---> Dechiper Load problem
> 
> 1684673953136: AMELI-> Exception: enc
> 
> 1684673953136: AMELI---> java.lang.Exception: Could not
> 
> parse deobfuscate function 1684673953136:
> 
> AMELI>Sorting
> 
> AMELI---> URL https://youtu.be/uDFIVtMAIZK
> 
> AMELI--> Detected extractor None AMELI---> URL https://youtu.be/uDFIVtMAIZK
> 
> AMELI---> Detected extractor YouTube
> 
> Also, there is no option to change the default download manager. Can you provide the option to change download manager in future releases?
> 

It says video is unavailable,so there's no way for me to reproduce the issue.

Also,you can change download managers by going to settings>revanced extended>overlay button>downloader settings

**Comment by NoName-exe** [comment]
> it's been many days but no new update 

Yeah unfortunately,I was too busy with IRL stuff.

**Pull request closed without merging**
