### PR TITLE
Link to maintained MicroG

### PR DESCRIPTION
**Pull request by kubo6472**

### CODE REVIEW

**Comment by amaan511** [comment]
I can't seem to add a request so I'm commenting here, are there any plans to add distraction free features on extended? Just like how it's there on Unhook Extension available on Chrome/Kiwi browser

**Comment by NoName-exe** [comment]
> I can't seem to add a request so I'm commenting here, are there any plans to add distraction free features on extended? Just like how it's there on Unhook Extension available on Chrome/Kiwi browser

Those decisions aren't up to me. And afaik rvx won't be getting much new features,if at all.

**Comment by WildFyr16** [comment]
I don't know how to work these things without an issue tracker so I'm just going to comment on this one. In the latest release v18.33.40 I have noticed it no longer saves my playback speed at 1.75 and instead reverts back to normal every new video. Has this issue come to your attention yet? (Again sorry for commenting here I just couldn't find the issue panel and every time I entered /issues it brought me to the pull requests)

**Comment by NoName-exe** [comment]
> I don't know how to work these things without an issue tracker so I'm just going to comment on this one. In the latest release v18.33.40 I have noticed it no longer saves my playback speed at 1.75 and instead reverts back to normal every new video. Has this issue come to your attention yet? (Again sorry for commenting here I just couldn't find the issue panel and every time I entered /issues it brought me to the pull requests)

I don't use that particular feature,so I have no idea,sorry. You can file a bug report at rvx issue tracker.

**Pull request closed without merging**
